### ISSUE TITLE
FoldX Warning error

### ISSUE THREAD

**Issue by jdkjsd** [ELELAB/mutatex#127] opened 2022-06-10 19:20 UTC
Hi,
I got this error and I don't know how to solve it.
WARNING:root:FoldX exited with error for run MB44! Return code 255
any help, please?
Thanks.

**Comment by mtiberti** [comment] 2022-06-16 06:49
hi @jdkjsd, thanks for your interest, this means that FoldX exited with an error for that run (i.e. the run couldn't be completed). You should refer to the content of the `mutations` folder - you can likely find a directory corresponding to `MB44` and check the files therein. If you have used option `-l` when running it you should also have a `*.log` file with the FoldX output that should help you troubleshoot (otherwise you can rerun using option `-l`). If you can share more information about the content of your folder or log file we can try and see what the problem is.

**Comment by mtiberti** [comment] 2022-06-17 08:27
Great you found a solution!
Notice that we've never tried energy-minimising our frames from MD before using MutateX/FoldX, so I'm not sure what effect this would have on results. Anyhow, I'm happy to know it's working now so we can close the issue

**Closed by mtiberti** 2022-06-17 08:27 UTC
